language: node_js
node_js:
  - "7.4"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  # Node 5+ requires a C++11 standard compliant compiler, so we'll use gcc.
  # See more info at https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    # Requirement for installing Node 5+
    - CXX=g++-4.8

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# TODO: Right now Angular CLI does not work with Yarn
install:
  - npm install

script:
  # Code style/format check with tslint.
  - npm run lint
  # Unit tests.
  - npm run test
  # E2E tests.
  # TODO: Protractor seems to fail, skip it until we fix it
  - npm run e2e

# after_success: npm run deploy:ci

notifications:
  email:
    on_success: never
    on_failure: never
    on_start: never
